#!/bin/sh
arch=arm64
crosstool=aarch64-linux-gnu
version=5
dir=`dirname $0`/$arch/gcc-$version
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$dir/lib:$dir/lib/x86_64-linux-gnu
sudo rsync -ar $dir/$crosstool/ /usr/$crosstool/
$dir/bin/$crosstool-g++ $@
